version: "3.9"
services:

  node-application:
    build: .
    image: fernandodzay/second-brain-backend
    container_name: second-brain-backend
    ports:
      - "3013:3000"
    restart: always
    env_file:
      - .env
    networks:
      - internal_mysql_network

networks:
  internal_mysql_network:
    external: true
